### ISSUE TITLE
Combine daily and hourly weather entities

### ISSUE THREAD

**Issue by Scoop2389** [jaydeethree/Home-Assistant-weatherdotcom#11]
[New in Home Assistant 2023.9](https://www.home-assistant.io/blog/2023/09/06/release-20239/#weather-forecast-service), weather entities' forecast data can now be accessed via a service, allowing for one entity to have multiple types of forecasts (daily and hourly). The forecast attribute (which this integration is currently using) is now depreciated and will be removed in version 2024.3.

Could you please update this integration to remove the need for two entities and for future proofing?

**Comment by Scoop2389** [comment]
I can't figure out how to add the enhancement label. Feel free to add that whenever you can.

**Comment by jaydeethree** [comment]
Thanks for opening this issue! From my limited understanding this will break backwards compatibility with older versions of Home Assistant, so I'm going to wait a few weeks before I start working on this. That will give people some extra time to update to Home Assistant 2023.9.

**Comment by jaydeethree** [comment]
Just a heads up that I didn't forget about this - I'm planning to start work on it in the next 1-2 weeks.

**Comment by jaydeethree** [comment]
This is mostly done with https://github.com/jaydeethree/Home-Assistant-weatherdotcom/commit/85e5a4760a1525be6fe959ee2881107b852d3312 - I'm doing some final testing and then I'll push a new release with it if everything looks good.

**Comment by jaydeethree** [comment]
This is now available as version 1.1.0.
