### ISSUE TITLE
Documentation refers to deprecated hourly weather sensor

### ISSUE THREAD

**Issue by Valdorama** [jaydeethree/Home-Assistant-weatherdotcom#14]
The documentation includes the following statement: 

> Additionally, a weather.<LOCATION_NAME>_hourly entity will be created that contains hourly forecast data.

Presumably this is no longer the case since both the daily and hourly forecasts are encapsulated in the main weather.<LOCATION_NAME> sensor (to accommodate the new weather forecast structure in HA 2023.09+). 

Caused a bit of confusion trying to use the hourly forecast with the Hourly Weather Card since the old 'xxx_hourly' sensor was no longer available. Changed it to use the main sensor and everything is good.

**Comment by jaydeethree** [comment]
Oops, you're right - several things probably need to be updated in the README with the changes I made for v1.1.0. I'll work on that soon. Thanks for letting me know about this!

**Comment by jaydeethree** [comment]
Fixed in https://github.com/jaydeethree/Home-Assistant-weatherdotcom/commit/38608ed603b2886865b3e718d2226573c29266bb. Thanks again for reporting this!
