### ISSUE TITLE
No current cloud coverage (only in forecast)

### ISSUE THREAD

**Issue by ScottG489** [jaydeethree/Home-Assistant-weatherdotcom#17]
I switched over to this integration from AccuWeather and it's really nice. The only entity I still use from AccuWeather is cloud coverage.

It looks like this integration only provides cloud coverage in the forecast. Would it be possible to have an entity that provides the current cloud coverage? Or have it as an attribute on the weather entity?

Thanks again for your work on this integration :)

**Comment by jaydeethree** [comment]
Unfortunately this is a limitation of the Weather.com API used by this integration - cloud coverage information is available for forecasts but not for current conditions.

Forecast API docs: https://docs.google.com/document/d/1RY44O8ujbIA_tjlC4vYKHKzwSwEmNxuGw5sEJ9dYjG4/edit

Current conditions API docs: https://docs.google.com/document/d/1UOjfN1j54Ocmwj-zYCcHG_RM1tlNceW_qlzz0wVILXA/edit

The forecast API returns a `cloudCover` field that contains the cloud coverage as a percentage, which this integration then adds to the forecast data in Home Assistant. However the current conditions API only returns a `cloudCoverPhrase` field, which is less useful and is not a percentage [like Home Assistant expects](https://developers.home-assistant.io/docs/core/entity/weather/#properties). I suppose I could take the `cloudCoverPhrase` field and turn that into a sensor, but it only has four possible options (Clear, Partly Cloudy, Mostly Cloudy, and Cloudy) so it's not as useful as a percentage. It's better than nothing though, so I'll go ahead and add that soon.

**Comment by jaydeethree** [comment]
Added in version 1.1.3.
