### ISSUE TITLE
Check Weather.com API ('unexpected character: line 1 column 1 (char 0)',)

### ISSUE THREAD

**Issue by sviperz** [jaydeethree/Home-Assistant-weatherdotcom#20]
Might not be related, but stopped working after some HA component upgrade. Currently I have:

**Core 2023.12.0
Supervisor 2023.11.6**

Error message in the log:

```
This error originated from a custom integration.

Logger: custom_components.weatherdotcom.coordinator
Source: custom_components/weatherdotcom/coordinator.py:161
Integration: Weather.com (documentation, issues)
First occurred: 09:12:23 (628 occurrences)
Last logged: 23:27:33

Check Weather.com API ('unexpected character: line 1 column 1 (char 0)',)
```

**Comment by jaydeethree** [comment]
I haven't seen that error before, but it sounds like Home Assistant isn't getting data from the weather.com API. Can you access weather.com in a browser? It's a known issue that weather.com blocks traffic from some countries, so I'm wondering if they've started blocking more countries that weren't blocked before.

**Comment by sviperz** [comment]
Thanks for the input! It was me who reported about restrictions from some countries. So I have a setup on my router to route the traffic via VPN accordingly. Their IP has changed, so this setup was broken. I updated it and now it works again. Sorry for confusion.

**Comment by jaydeethree** [comment]
Cool, I'm glad to hear that fixed it :)
