### ISSUE TITLE
[Feature Request] Add additional Air Quality sensor

### ISSUE THREAD

**Issue by YeeYek** [jaydeethree/Home-Assistant-weatherdotcom#21]
Hello, 
Can you add one more sensor - Air Quality (AQI)?

**Comment by jaydeethree** [comment]
Unfortunately that information is not available in the API - here's a list of everything that is available:

https://docs.google.com/document/d/1UOjfN1j54Ocmwj-zYCcHG_RM1tlNceW_qlzz0wVILXA/edit

Home Assistant does have several built-in integrations for air quality though, so one of those might work for you:

https://www.home-assistant.io/integrations/#health
