### ISSUE TITLE
Integration failed to load after core 2024.2.0 update

### ISSUE THREAD

**Issue by GGSSDD** [jaydeethree/Home-Assistant-weatherdotcom#24]
Hi,
Any ideea why the integration is broken after HA core 2024.2.0 update? Can’t seem to make it work no matter what i do. And I’ve pretty much tried everything. It worked fine until last night when i updated the core. 
Logs below:

``` 
Logger: homeassistant.setup
Source: setup.py:251
First occurred: 17:31:22 (1 occurrences)
Last logged: 17:31:22

Setup failed for custom integration 'weatherdotcom': Unable to import component: No module named 'custom_components.weatherdotcom.coordinator'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 827, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/weatherdotcom/__init__.py", line 11, in <module>
    from .coordinator import WeatherUpdateCoordinator, WeatherUpdateCoordinatorConfig
ModuleNotFoundError: No module named 'custom_components.weatherdotcom.coordinator'

```

**Comment by jaydeethree** [comment]
I haven't had any issues since updating to 2024.2.0, everything has been working fine. Based on the log it sounds like something might be wrong with your installation of this component - can you try re-downloading it in HACS to see if that helps?

**Comment by GGSSDD** [comment]
I tried but is not working… it gets stuck in the loading stage, and i’ve discovered I have this timeout errors in HACS.

![IMG_1232](https://github.com/jaydeethree/Home-Assistant-weatherdotcom/assets/121240474/17723faf-b30d-4bfe-994f-6c2a46c52323)
![IMG_1233](https://github.com/jaydeethree/Home-Assistant-weatherdotcom/assets/121240474/5e8551db-6b28-436f-889c-3bf924b508e0)

**Comment by jaydeethree** [comment]
Something seems to be wrong with your Home Assistant server. This is the error you're getting:

>ModuleNotFoundError: No module named 'custom_components.weatherdotcom.coordinator'

That means that this integration (the Weather.com integration) is not fully installed or its files are corrupt - that's why I suggested reinstalling the integration through HACS. However the screenshots you provided show that HACS is not able to download files from GitHub, which indicates some sort of network problem on your side.

I'm not 100% sure what's going on here, but I'm pretty confident the issue is on your side. Unfortunately that means that there's nothing I can do to fix it :(

**Comment by GGSSDD** [comment]
That’s right… I tried to reinstall the integration but I can’t, because of all this timeout errors I get in my setup, and it’s not only HACS that’s affected but my whole setup… I got a lot of updates pending, including for weather.com but I can’t do a damn thing about it.
