### ISSUE TITLE
"feels like

### ISSUE THREAD

**Issue by francis110** [jaydeethree/Home-Assistant-weatherdotcom#25]

**Comment by jaydeethree** [comment]
I think this issue was opened by accident, see this:

https://github.com/jaydeethree/Home-Assistant-weatherdotcom/discussions/26

However I'm going to keep this bug open to track adding the `native_apparent_temperature` property to the weather entity.

**Comment by jaydeethree** [comment]
Fixed in https://github.com/jaydeethree/Home-Assistant-weatherdotcom/commit/217e0df6b6a7e56103004ca1336102e459a7c435, now available as version 1.1.5.
