### ISSUE TITLE
License

### ISSUE THREAD

**Issue by eutampieri** [jaydeethree/Home-Assistant-weatherdotcom#31]
Which license is this work licensed under?
I'd wish to create a fork for another weather provider, but without a license I cannot proceed. You can choose one here: https://choosealicense.com/

**Comment by jaydeethree** [comment]
Thanks for letting me know that this was missing! I've added a license in https://github.com/jaydeethree/Home-Assistant-weatherdotcom/commit/db03609a435dca56a934a82ed5dad0b29038869b (GPLv3).

**Comment by eutampieri** [comment]
Thanks ☺️
