### ISSUE TITLE
add a sensor for cloud coverage

### ISSUE THREAD

**Issue by esdcmc** [jaydeethree/Home-Assistant-weatherdotcom#34]
would it be possible to all scrape the information of cloud coverage (in %) and get that into a sensor? I see in wunderground that the info is available when I click the HOURLY tab

thanks

**Comment by jaydeethree** [comment]
Hourly cloud coverage data is already available in the weather.LOCATION_NAME entity:

https://github.com/jaydeethree/Home-Assistant-weatherdotcom/blob/master/custom_components/weatherdotcom/weather.py#L244-L245

![cloudcover](https://github.com/user-attachments/assets/66ef365e-bf6f-4316-b260-27ae44dfb506)

**Comment by esdcmc** [comment]
great!
thank-you
