### ISSUE TITLE
Data loss after HA upgrade

### ISSUE THREAD

**Issue by Abejo** [jaydeethree/Home-Assistant-weatherdotcom#35]
Hi, with the latest HA update I lose the forecast, for now I solved it by creating an automation that reloads the service every 10 minutes.

**Comment by jaydeethree** [comment]
Thanks for reporting this issue! I have not updated to HA 2024.8 yet, and I won't have time to update and debug this for at least a couple of days. Let me know if you see any error messages in the HA logs, and I'll plan to take a look at this as soon as I have time.

**Comment by Abejo** [comment]
I'm noticing that the connection is very slow, that could be the problem and it started right after the update, I'm going to keep trying to see if it normalizes or if the error continues.
Thanks

**Comment by jaydeethree** [comment]
I have not been able to reproduce this issue on Home Assistant 2024.8 - everything seems to be working normally. Since I can't reproduce this and it sounds like a potential network issue, I'm going to mark this as closed.
