### ISSUE TITLE
Unknown Error after inserting the apiKey

### ISSUE THREAD

**Issue by Disincentivato** [jaydeethree/Home-Assistant-weatherdotcom#36]
Hi,
I get this error:

![image](https://github.com/user-attachments/assets/e51c119c-8a5b-4f81-b8f7-bd561eb9cb17)

**Comment by jaydeethree** [comment]
Can you check your Home Assistant logs (Settings > System > Logs)? There may be more details there about what's happening.

**Comment by Disincentivato** [comment]
This error originated from a custom integration.

Logger: custom_components.weatherdotcom.config_flow
Source: custom_components/weatherdotcom/config_flow.py:73
integration: weatherdotcom (documentation, issues)
First occurred: 07:51:30 (8 occurrences)
Last logged: 18:29:05

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/weatherdotcom/config_flow.py", line 73, in async_step_user
    raise Exception
Exception

**Comment by jaydeethree** [comment]
I'm pretty sure that's a network error, which means Home Assistant can't access the weather.com API. Can you try going to weather.com in a browser that's on the same network as Home Assistant?

**Comment by Disincentivato** [comment]
> I'm pretty sure that's a network error, which means Home Assistant can't access the weather.com API. Can you try going to weather.com in a browser that's on the same network as Home Assistant?

Hi, thanks for your help on this.. no all the web browser on the same network can connect without problem to the weather.com or https://www.wunderground.com/...
I tried searching for apikey in the weather.com source code and it worked. Thanks again!

**Comment by jaydeethree** [comment]
Thanks for the update, I'm glad it's working now!
