### ISSUE TITLE
Lat and long not updating

### ISSUE THREAD

**Issue by MarkGTI** [jaydeethree/Home-Assistant-weatherdotcom#40]
I moved location (800 miles further south) and my lat and long are still pointing at my old address (HA has been up for 8 hours and has restarted)

When and how does it update the lat and long and how can I force it.

**Comment by jaydeethree** [comment]
Lat/long will not update automatically - the only way to update them is to set up the integration again (Settings > Devices & Services > Add Integration). The reason for this is that if you're changing your lat/long you probably also want to change the location name, and that can only be changed by setting up the integration from scratch again. For example if you moved from Chicago to Houston you probably wouldn't want your Houston weather entities to still be named `Chicago`.

Let me know if you need any other info about this!
