### ISSUE TITLE
How to show Precipitation Probability?

### ISSUE THREAD

**Issue by xitters** [jaydeethree/Home-Assistant-weatherdotcom#42]
![image](https://github.com/user-attachments/assets/f95463b8-d3f9-4c0e-872d-2b451e71a885)

I dont see any attibute for this

**Comment by jaydeethree** [comment]
Home Assistant does not make forecast data available in the entity's attributes - you have to use the `weather.get_forecasts` action. There's some info about that in [the Home Assistant weather docs](https://www.home-assistant.io/integrations/weather/#action-weatherget_forecasts) - take a look at the "Example template sensor using get_forecasts" section for an example of how to create sensors from that data.

**Comment by xitters** [comment]
just now find it hahah. Thanks!
![image](https://github.com/user-attachments/assets/4d5b9a61-5212-4bdb-b1b7-9d618081829e)
