### ISSUE TITLE
Error fetching Weather.com data: TimeoutError() after update to 1.1.9

### ISSUE THREAD

**Issue by ncd7** [jaydeethree/Home-Assistant-weatherdotcom#43]
Getting the below after the most recent update. Any ideas?

```
2024-11-12 17:19:51.699 ERROR (MainThread) [custom_components.weatherdotcom.coordinator] Error fetching Weather.com data: TimeoutError()
2024-11-12 17:19:51.700 DEBUG (MainThread) [custom_components.weatherdotcom.coordinator] Finished fetching WeatherUpdateCoordinator data in 10.003 seconds (success: False)
```

**Comment by jaydeethree** [comment]
I had very similar errors at the time that you opened this issue, but the errors went away on their own. Based on that and the fact that these were timeout errors I suspect there was a temporary issue with the Weather.com API that has already been fixed. Can you please try again and let me know if you're still seeing errors? Thanks!

**Comment by jaydeethree** [comment]
I'm not sure what's going on, but I typically see 1-2 failures per day connecting to the API. Some days are worse and have 5 or more connection failures. Unfortunately if the API is down there's nothing I can do, we just have to wait for it to come back up.

**Comment by jaydeethree** [comment]
I just committed some changes that attempt to improve reliability:

https://github.com/jaydeethree/Home-Assistant-weatherdotcom/commit/4cd361682dd165f52a42dcd25c3267c1865ef47a

Of course if the Weather.com API is completely down then there's nothing we can do about that, but this will hopefully help with network glitches and other temporary issues. I'm going to test these changes for a few days before I make a new release with them.
