### ISSUE TITLE
Unable to create an API key

### ISSUE THREAD

**Issue by Sythsaz** [jaydeethree/Home-Assistant-weatherdotcom#44]
According to the Weather Underground website: "No API key. You must own a Personal Weather Station in order to generate an API key.". Any help would be appreciated, thanks! There is also nothing in the page source called "apiKey" other than styling and scripts

**Comment by jaydeethree** [comment]
I just checked and I'm still seeing the key in the page source. Make sure you're looking at the source for https://www.wunderground.com/ and not a different page on their site.

**Comment by Sythsaz** [comment]
i see i had to right click to view it instead of using the Developer Tools... Thanks for your help!
