### ISSUE TITLE
Fix install docs now that it's a HACS default integration

### ISSUE THREAD

**Issue by ScottG489** [jaydeethree/Home-Assistant-weatherdotcom#6]
Looks like this was [added as a default to HACS](https://github.com/hacs/default/commit/381562cd56f92a62d5a7831cbac29157babb1e61) so the README shouldn't say it needs to be installed as a custom repo.

Excited to try this out! Weather.com has the most accurate and detailed forecasts from what I've seen.

**Comment by jaydeethree** [comment]
Done:

https://github.com/jaydeethree/Home-Assistant-weatherdotcom/commit/c3d99fe50212d800777486bcbcf3337501c73bc5

Thanks for pointing this out!
