### ISSUE TITLE
API key

### ISSUE THREAD

**Issue by pepsonEL** [jaydeethree/Home-Assistant-weatherdotcom#9]
Hi
I am from POLAND and i have a problem with API Key. Still get info Invalid API Key. Also generate this api by connect by Free VPN to USA and then go to https://www.wunderground.com/ and generate and still is invalid. Can you help me please?

**Comment by jaydeethree** [comment]
Does your API key end in `96f525`? That's the only API key that is tested/supported - if you're using a different one then that might be why it doesn't work.

**Comment by pepsonEL** [comment]
No my API end in 41d264, i can not generate API with end in 96f525

**Comment by jaydeethree** [comment]
What do you mean when you say you're generating an API key? You shouldn't need to generate anything - you should just go to https://www.wunderground.com/, view the page's source, and then search for `apiKey` in the source. If you're generating a custom API key with a Wunderground account (like the account you use for a Personal Weather Station) then that won't work.

**Comment by pepsonEL** [comment]
But when i go to API Key i have this info:

No API key. You must own a Personal Weather Station in order to generate an API key.

**Comment by jaydeethree** [comment]
You need to just go to https://www.wunderground.com/ - don't click any links on the page and don't login. Then view the page's source and search for `apiKey` in it. That should be all you need to do.

**Comment by pelentron** [comment]
жаль , не рабоатет! мой API c048413a870b40f388413a870be0f39e

**Comment by jaydeethree** [comment]
Sorry, but unfortunately I can't help - only the US API key has been tested with this integration, and other API keys are not supported. Please check the README for more details about this:

https://github.com/jaydeethree/Home-Assistant-weatherdotcom#weathercom-api-key

**Comment by pepsonEL** [comment]
> You need to just go to https://www.wunderground.com/ - don't click any links on the page and don't login. Then view the page's source and search for `apiKey` in it. That should be all you need to do.


Sorry but i try searcgh in source code page but i dont find this apikey... Can you show me where ?

**Comment by jaydeethree** [comment]
Sure, this is what I see in Firefox:

![Screenshot 2023-09-17 120322](https://github.com/jaydeethree/Home-Assistant-weatherdotcom/assets/34945248/c5b1950d-f0ef-4a7d-8a7b-8e3b7ee08d59)

**Comment by pepsonEL** [comment]
ok i found apikey with end xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx96f525&a but when put it to integration and try save i get info UNKNOWN ERROR.

**Comment by jaydeethree** [comment]
Remove the `&a` - that's not part of the API key. It should just end in `96f525`.

**Comment by pepsonEL** [comment]
Thanks and works :)
